FROM python:3.9-slim

WORKDIR /app

# Install iperf3
RUN apt-get update && apt-get install -y \
    iperf3 \
    && rm -rf /var/lib/apt/lists/*

COPY echo_server.py /app/voip/
COPY start_echo.sh /app/voip/
COPY VERSION /app/

RUN chmod +x /app/voip/start_echo.sh

EXPOSE 6100/udp
EXPOSE 5201/tcp
EXPOSE 5201/udp

ENTRYPOINT ["/app/voip/start_echo.sh"]
